# Generated by Django 4.1.4 on 2023-02-17 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now=True)),
                ('punctuality', models.CharField(choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Sometimes', 'Sometimes'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=225, verbose_name='The teacher is punctual in coming to class')),
                ('portion', models.CharField(choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Sometimes', 'Sometimes'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=225, verbose_name='The teacher completes portions at the appropriate time')),
                ('doubt', models.CharField(choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Sometimes', 'Sometimes'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=225, verbose_name='The teacher takes in effort to clear your doubts')),
                ('interactive', models.CharField(choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Sometimes', 'Sometimes'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=225, verbose_name='The teacher makes the class interactive')),
                ('comments', models.TextField(blank=True, verbose_name='Any other feedback (your comments)')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.teacher', verbose_name='Name of Teacher')),
            ],
            options={
                'verbose_name': 'Feedback Data',
                'verbose_name_plural': 'Feedback Data',
            },
        ),
    ]
