# Generated by Django 4.1.4 on 2023-02-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdata',
            name='interactive',
            field=models.CharField(choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Sometimes', 'Sometimes'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], max_length=225, verbose_name='Namra...'),
        ),
    ]
