# Generated by Django 4.1.7 on 2023-03-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Review", "0005_remove_faculty_semester_faculty_semester"),
        ("Feedback", "0004_alter_feedbackdata_teacher_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackdata",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Review.semester",
                verbose_name="Semester",
            ),
        ),
    ]
