# Generated by Django 4.1.7 on 2023-03-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Feedback", "0006_feedbackdata_average_feedbackdata_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackdata",
            name="average",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="feedbackdata",
            name="total",
            field=models.PositiveIntegerField(),
        ),
    ]
