# Generated by Django 4.1.4 on 2023-02-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
