# Generated by Django 4.1.4 on 2023-02-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0002_remove_user_phone_user_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identity',
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='20CEUOS000', max_length=10),
        ),
    ]
