# Generated by Django 4.1.7 on 2023-03-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Review", "0004_semester_subject_faculty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="semester",
        ),
        migrations.AddField(
            model_name="faculty",
            name="semester",
            field=models.ManyToManyField(
                blank=True, related_name="faculties", to="Review.semester"
            ),
        ),
    ]
