# Generated by Django 4.1.7 on 2023-03-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Review", "0005_remove_faculty_semester_faculty_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="semester",
            field=models.ManyToManyField(
                blank=True, related_name="semester", to="Review.semester"
            ),
        ),
    ]
