# Generated by Django 4.1.7 on 2023-03-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Review", "0007_alter_faculty_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="semester",
        ),
        migrations.AddField(
            model_name="faculty",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Review.semester",
            ),
        ),
    ]
