# Generated by Django 4.1.7 on 2023-03-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Review", "0009_remove_faculty_semester_faculty_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="subject",
        ),
        migrations.AddField(
            model_name="faculty",
            name="subject",
            field=models.ManyToManyField(to="Review.subject"),
        ),
    ]
